version: '3'

services:
  postgres:
    container_name: wemo_e2e_postgres
    image: postgres:14.5
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    container_name: wemo_e2e_api
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - postgres
